### ISSUE TITLE
`body.expiration` not supported

### ISSUE THREAD

**Issue by jonathan-wondereur** [Bandwidth/ruby-sdk#21]
It seems like the Ruby library does not support he `body.expiration` property to not send a message if it takes too long.

Please add support for this.

https://dev.bandwidth.com/messaging/methods/messages/createMessage.html

**Comment by ajrice6713** [comment]
Hey Jonathan,

I appreciate you pointing this out - it looks like the `expiration` field is not present in our API spec - which is where we generate the SDKs from. 

I am reaching out to the appropriate teams to get that added to the spec and we will push an update in all languages as soon as that is complete - it shouldn't take long at all as this is a pretty simple addition.

**Comment by ckoegel** [comment]
Hey @jonathan-wondereur, sorry for the long wait, but this is going to be added in v10.3.0, releasing Tuesday, March 14th. The `expiration` field will also be present in the v11.0.0.pre.beta.1.1 version of the SDK, which will be releasing in the next day or so. I'd encourage you to check out the v11 beta since it will be the next major version of the SDK and will be a complete overhaul with lots of improvements.
