### ISSUE TITLE
Outdated version of certifi / dependency on certifi

### ISSUE THREAD

**Issue by gavingmiller** [Bandwidth/ruby-sdk#84]
The bandwidth sdk [uses a 5 year outdated version of the `certifi` gem](https://github.com/Bandwidth/ruby-sdk/blob/main/bandwidth.gemspec#L16) that is not having its certificate set updated. As a result, trust could be extended to entities that ought not have that trust set. An example is [TrustCor which was revoked by Mozilla](https://www.washingtonpost.com/technology/2022/11/30/trustcor-internet-authority-mozilla/), but is still [present in the mentioned gem](https://github.com/certifi/ruby-certifi/blob/master/lib/certifi/vendor/cacert.pem#L3997-L4105).

Can this dependency be removed from the gem, or an update to cetifi be made to use a modern set of certificate authorities.

**Comment by ckoegel** [comment]
Hey @gavingmiller, thanks for the Issue. We've known about that outdated certifi dependency for a little bit now, but it took a backseat to the new v11 beta. I'm going to make a PR soon that removes that certifi dependency (since the project hasn't been touched since 2018) from this version of the SDK, which should get released in v10.3.0 on Tuesday, March 14th. I'd advise you to also check out the [v11 beta](https://rubygems.org/gems/bandwidth-sdk/versions/11.0.0.pre.beta.1), which is set to be our next major version of the SDK coming out later this year. It's 100% breaking since we've switched to the OpenAPI Generator project for generation, but it's better in pretty much every way, and it also fixes this certifi issue :)
